result_dir: 'results'
#exp_name: ''
lr: 0.001
total_kimg: 6000
#resume_network: ''  # 001-test/network-snapshot-{}-000025.dat
num_data_workers: 0
random_seed: 1373
grad_lambda: 10.0  # must set it to zero to disable gp loss (even for non wgan(10.0) based losses)
iwass_drift_epsilon: 0.001
iwass_target: 1.0
feature_matching_lambda: 0.0
loss_type: 'wgan_gp'  # wgan_gp, hinge, wgan_theirs, rsgan, rasgan, rahinge
cuda_device: 0
ttur: false
#config_file: null
fmap_base: 1024
fmap_max: 256
fmap_min: 64
equalized: true
kernel_size: 3
self_attention_layers: []  # starts from 0 or null (for G it means putting it after ith layer)
random_multiply: false
lr_rampup_kimg: 0.0 # used to be 40
z_distribution: 'normal' # normal, bernoulli, censored
init: 'kaiming_normal' # kaiming_normal, xavier_uniform, orthogonal
act_alpha: 0.2
residual: false
calc_swd: false
separable: false
num_classes: 0
deep: false

Trainer:
  d_training_repeats: 5 # used to be 1 and 2 in big-gan
  tick_kimg_default: 5.0

Generator:
  spectral: false
  latent_size: 256
  no_tanh: false
  per_channel_noise: false
  to_rgb_mode: 'pggan' # pggan, sagan, sngan
  split_z: false
  dropout: 0.2
  act_norm: 'pixel' # pixel, batch, layer, None
  normalize_latents: true
  z_to_bn: false
  conv_only: false
  shared_embedding_size: 32
  rgb_generation_mode: 'pggan' # msg, residual, mean, pggan

Discriminator:
  spectral: false
  dropout: 0.2
  act_norm: null # pixel, batch, layer, None
  group_size: 4
  temporal_groups_per_window: 1
  conv_only: false
  input_to_all_layers: false

Adam:
  betas: !!python/tuple [0.0, 0.99]
  eps: 0.00000001
  weight_decay: 0

DepthManager:
  reset_optimizer: true
  disable_progression: false
  depth_offset: 0  # starts form 0
  minibatch_default: 256
  lod_training_kimg: 400
  lod_transition_kimg: 400

SaverPlugin:
  keep_old_checkpoints: true
  network_snapshot_ticks: 50

SlicedWDistance:
  patches_per_item: 16
  patch_size: 49
  max_items: 1024
  number_of_projections: 512
  dir_repeats: 4
  dirs_per_repeat: 128

OutputGenerator:
  samples_count: 8
  output_snapshot_ticks: 25
  old_weight: 0.95

EfficientLossMonitor:
  monitor_threshold: 10.0
  monitor_warmup: 50
  monitor_patience: 5

EEGDataset:
  dir_path: './data/prepared_eegs_mat_th5/'
  data_sampling_freq: 220
  start_sampling_freq: 1
  end_sampling_freq: 60
  start_seq_len: 32
  num_channels: 17
  return_long: false

WatchSingularValues:
  one_divided_two: 10.0
  output_snapshot_ticks: 20
